/**
 * Emit a `.d.ts` file augmenting `NodeTypeRegistry` with typed config
 * shapes, one entry per node type. The emitter is a pure function over
 * the schemas captured by `extractNodeSchemas` — no I/O, no server
 * calls — so it's snapshot-tested against checked-in fixtures.
 *
 * Schema surface this handles (everything observed in the live
 * `getWorkflowSchema()` output):
 *
 * - `properties` + `required` (the bulk of node configs)
 * - `enum` on string fields → string-literal union
 * - `x-enum` (advisory enum, server doesn't enforce) → plain `string`
 * - `oneOf` in two flavours: branches with only `required`
 *   (script-style: a key is required-XOR), and branches with their own
 *   `properties` containing constrained `enum`s (join-style:
 *   strategy-discriminated)
 * - `type: object` with no inner `properties` → `Record<string, unknown>`
 * - Empty schema (split) → `Record<string, never>`
 * - Lua-bearing string fields (annotated `x-editor: "code"`,
 *   `x-editorLanguage: "lua"`, OR matching the field-name allowlist)
 *   → `string | LuaFileMarker`
 */

import type { NodeSchemaMap } from "./extract-node-schemas.ts";

/**
 * Field names that should accept `luaFile()` even when the schema
 * lacks the `x-editor: "code"` + `x-editorLanguage: "lua"` annotations.
 * Belt-and-braces: the extension-based check is the primary signal,
 * this list catches the cases where the server schema hasn't been
 * annotated yet.
 */
const LUA_FIELD_ALLOWLIST = new Set(["inline", "source", "script", "luaSource"]);

type JSONSchema = {
  type?: string;
  properties?: Record<string, JSONSchema>;
  required?: string[];
  enum?: string[];
  items?: JSONSchema;
  oneOf?: JSONSchema[];
  description?: string;
  "x-enum"?: string[];
  "x-editor"?: string;
  "x-editorLanguage"?: string;
  "x-supportsExpression"?: boolean;
  "x-relatedResource"?: string;
  [key: string]: unknown;
};

export type EmitOptions = {
  /**
   * Hex digest written into the file header so a reader can confirm
   * which schema snapshot the file was generated from.
   */
  digest: string;
  /**
   * Which registry interface to augment. The shipped baseline writes
   * to `NodeTypeRegistry`; workspace `cococo update` writes to
   * `WorkspaceNodeTypeRegistry` so the two never conflict on shared
   * keys.
   */
  registry?: "NodeTypeRegistry" | "WorkspaceNodeTypeRegistry";
};

export function emitNodeTypes(schemas: NodeSchemaMap, opts: EmitOptions): string {
  const registry = opts.registry ?? "NodeTypeRegistry";
  const types = Object.keys(schemas).sort();
  const usesLuaMarker = types.some((t) => schemaUsesLuaMarker(schemas[t]!));
  const usesJSONLogic = types.some((t) => schemaUsesJSONLogic(schemas[t]!));

  const imports: string[] = [];
  if (usesLuaMarker) imports.push("LuaFileMarker");
  if (usesJSONLogic) imports.push("JSONLogicExpression");

  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by 'cococo update'. Do not edit by hand.`);
  lines.push(`// Schema digest: ${opts.digest}`);
  lines.push(``);
  if (imports.length > 0) {
    lines.push(
      `import type { ${imports.join(", ")} } from "@wearecococo/dev-cli/define";`,
    );
    lines.push(``);
  }
  lines.push(`declare module "@wearecococo/dev-cli/define" {`);
  lines.push(`  interface ${registry} {`);

  for (const type of types) {
    const schema = schemas[type]!;
    const tsType = emitConfigType(schema, /*indent*/ "    ");
    lines.push(`    ${quoteKeyIfNeeded(type)}: ${tsType};`);
  }

  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function emitConfigType(schema: JSONSchema, indent: string): string {
  if (schema.oneOf && schema.oneOf.length > 0) {
    return emitOneOf(schema, indent);
  }
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  if (Object.keys(props).length === 0) {
    return "Record<string, never>";
  }
  return emitObject(props, required, indent);
}

function emitOneOf(schema: JSONSchema, indent: string): string {
  const topProps = schema.properties ?? {};
  const topRequired = schema.required ?? [];
  const branches = schema.oneOf!;

  const branchTypes = branches.map((branch) => {
    // Per-branch property override: branch.properties replaces top-level
    // entries with the same key. (Used by join-style to narrow `strategy`.)
    const branchProps = branch.properties ?? {};
    const mergedProps: Record<string, JSONSchema> = { ...topProps };
    for (const [k, v] of Object.entries(branchProps)) {
      mergedProps[k] = v;
    }
    const required = new Set([...topRequired, ...(branch.required ?? [])]);
    return emitObject(mergedProps, required, indent);
  });

  return branchTypes.join(" | ");
}

function emitObject(
  properties: Record<string, JSONSchema>,
  required: Set<string>,
  indent: string,
): string {
  const keys = Object.keys(properties).sort();
  if (keys.length === 0) return "Record<string, never>";

  const inner = indent + "  ";
  const fields = keys.map((key) => {
    const fieldSchema = properties[key]!;
    const fieldType = emitFieldType(fieldSchema, key, inner);
    const opt = required.has(key) ? "" : "?";
    return `${inner}${quoteKeyIfNeeded(key)}${opt}: ${fieldType}`;
  });

  return `{\n${fields.join(";\n")};\n${indent}}`;
}

function emitFieldType(schema: JSONSchema, fieldName: string, indent: string): string {
  // Real enum (server-enforced) → string-literal union.
  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  // x-enum is advisory only; the server doesn't constrain. Treat as plain string
  // so author code isn't artificially restricted.

  if (isLuaCodeField(schema, fieldName)) {
    return "string | LuaFileMarker";
  }

  if (isJSONLogicField(schema)) {
    return "JSONLogicExpression";
  }

  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "object": {
      const inner = schema.properties;
      if (inner && Object.keys(inner).length > 0) {
        return emitObject(inner, new Set(schema.required ?? []), indent);
      }
      return "Record<string, unknown>";
    }
    case "array": {
      const items = schema.items;
      if (!items) return "unknown[]";
      if (items.type === "object" && items.properties) {
        return `Array<${emitObject(items.properties, new Set(items.required ?? []), indent)}>`;
      }
      return `Array<${emitFieldType(items, fieldName, indent)}>`;
    }
    default:
      return "unknown";
  }
}

/**
 * Detect fields that the server treats as JSONLogic. The schema
 * doesn't currently carry an explicit `x-format: "jsonlogic"`
 * extension, so we pattern-match on the description (which is very
 * consistent across the affected node types — "JSONLogic expression",
 * "JSONLogic predicate", etc.). If a future schema starts emitting
 * an extension, prefer that signal.
 */
function isJSONLogicField(schema: JSONSchema): boolean {
  if (schema.type !== "object") return false;
  // Don't override schemas with their own structured properties — we
  // want JSONLogicExpression only on the freeform-object form.
  if (schema.properties && Object.keys(schema.properties).length > 0) return false;
  const desc = schema.description;
  if (typeof desc !== "string") return false;
  return /json\s*logic/i.test(desc);
}

function schemaUsesLuaMarker(schema: JSONSchema): boolean {
  return findLuaMarker(schema);
}

function schemaUsesJSONLogic(schema: JSONSchema): boolean {
  return findJSONLogic(schema);
}

function findJSONLogic(schema: JSONSchema): boolean {
  if (isJSONLogicField(schema)) return true;
  if (schema.properties) {
    for (const prop of Object.values(schema.properties)) {
      if (findJSONLogic(prop)) return true;
    }
  }
  if (schema.items && findJSONLogic(schema.items)) return true;
  if (schema.oneOf) {
    for (const branch of schema.oneOf) {
      if (findJSONLogic(branch)) return true;
    }
  }
  return false;
}

function findLuaMarker(schema: JSONSchema): boolean {
  if (schema.properties) {
    for (const [name, prop] of Object.entries(schema.properties)) {
      if (isLuaCodeField(prop, name)) return true;
      if (findLuaMarker(prop)) return true;
    }
  }
  if (schema.items && findLuaMarker(schema.items)) return true;
  if (schema.oneOf) {
    for (const branch of schema.oneOf) {
      if (findLuaMarker(branch)) return true;
    }
  }
  return false;
}

function isLuaCodeField(schema: JSONSchema, fieldName: string): boolean {
  if (schema.type !== "string") return false;
  if (schema["x-editor"] === "code" && schema["x-editorLanguage"] === "lua") {
    return true;
  }
  return LUA_FIELD_ALLOWLIST.has(fieldName);
}

/**
 * TypeScript identifier rules: `[A-Za-z_$][A-Za-z0-9_$]*`. Anything
 * else (e.g. node-type keys with underscores like `http_request` are
 * fine, but pre-emptively quote anything we're not sure about) gets
 * a string-literal key.
 */
function quoteKeyIfNeeded(key: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) return key;
  return JSON.stringify(key);
}
